### ISSUE TITLE
作者你好，数据集中 "data/ACM/ACM.pkl" 文件的shape 和模型中似乎对应不上

### ISSUE THREAD

**Issue by ZhangIceNight** [limengran98/HGTN#1]
作者你好，数据集中 "data/ACM/ACM.pkl" 文件的shape 和模型中似乎对应不上

报错如下：

`RuntimeError: Error(s) in loading state_dict for AE:                                                                                                                          
        Unexpected key(s) in state_dict: "enc_2.weight", "enc_2.bias", "enc_3.weight", "enc_3.bias", "dec_1.weight", "dec_1.bias", "dec_2.weight", "dec_2.bias", "dec_3.weight", "dec_3.bias", "x_bar_layer.weight", "x_bar_layer.bias". 
        size mismatch for enc_1.weight: copying a param with shape torch.Size([500, 334]) from checkpoint, the shape in current model is torch.Size([128, 334]).
        size mismatch for enc_1.bias: copying a param with shape torch.Size([500]) from checkpoint, the shape in current model is torch.Size([128]).
        size mismatch for z_layer.weight: copying a param with shape torch.Size([10, 2000]) from checkpoint, the shape in current model is torch.Size([20, 128]).
        size mismatch for z_layer.bias: copying a param with shape torch.Size([10]) from checkpoint, the shape in current model is torch.Size([20]).`

**Comment by limengran98** [comment]
您可将超参数node_dim的值修改为10

**Comment by CCCCCCCJA** [comment]
> 

你好，改了之后还是报这个错误
报错如下：
RuntimeError: Error(s) in loading state_dict for AE:
        Unexpected key(s) in state_dict: "enc_2.weight", "enc_2.bias", "enc_3.weight", "enc_3.bias", "dec_1.weight", "dec_1.bias", "dec_2.weight", "dec_2.bias", "dec_3.weight", "dec_3.bias", "x_bar_layer.weight", "x_bar_layer.bias". 
        size mismatch for enc_1.weight: copying a param with shape torch.Size([500, 1870]) from checkpoint, the shape in current model is torch.Size([128, 1870]).
        size mismatch for enc_1.bias: copying a param with shape torch.Size([500]) from checkpoint, the shape in current model is torch.Size([128]).
        size mismatch for z_layer.weight: copying a param with shape torch.Size([10, 2000]) from checkpoint, the shape in current model is torch.Size([10, 128]).

**Comment by limengran98** [comment]
生成pkl的代码文件已上传，您可根据您的需求保证预训练模型与HGTN中AE模块的模型维度一致即可。

**Comment by Leesnxw** [comment]
作者你好, 请问代码中为什么找不到GAT? 
报错如下;

Traceback (most recent call last):
  File "D:\Learn\PycharmProjects\Meta-path\HGTN\main.py", line 354, in <module>
    model = HGTN(type_hyperedge=A.shape[-1],
  File "D:\Learn\PycharmProjects\Meta-path\HGTN\HGTN.py", line 59, in __init__
    self.gat = GAT(self.w_in,self.nhid,self.num_class,self.drpoput ,self.alpha ,self.nheads)
NameError: name 'GAT' is not defined
